# Site settings
title: Aroon Chande's CV 
description: Aroon Chande's CV 
favicon: /assets/img/avatar.JPG
baseurl: https://www.aroonchan.de
url: https://www.aroonchan.de
rss_url: /pages/atom.xml
google_analytics: UA-45174995-10

# Build settings
markdown: kramdown

exclude: [vendor]

# Author settings
author:
  name: Aroon Chande
  title: Bioinformatics Scientist
  address: Atlanta, Georgia
  email: mail@aroonchande.com
  link: https://aroonchande.com
  github: ar0ch
  # linkedin: ddbullfrog
  # twitter: ddbullfrog
  gavatar: /assets/img/avatar.JPG
  # stackoverflow:
#  stackoverflow: 4582127
  workHistory:
    - work1:
      company: Applied Bioinformatics Laboratory
      location: 2 Ravinia Dr. Suite 1200, Atlanta GA 30346
      title: Bioinformatics Scientist
      started: 2016
      duration: (2016 - Present)
      description: Bioinformatics consulting, adult continuing education and workforce development.  Development and maintenance of analytics platforms.  Development and maintenance of custom bioinformatics databases/
    - work2:
      company: Apicella Laboratory
      location: University of Iowa, Iowa City, IA
      title: Research Assistant
      started: 2011
      duration: (2011 - 2015)
      description: Development of expression and purification systems for recombinant bacterial proteins.  Screening and data collection on crystallized nuclease in-house and Synchrotron radiation (4.2.2 beamline at ALS, Berkeley).  Biological assays for protein activity, targets and pH dependence.  Biofilm, immunoassay and confocal microscopy
    - work3:
      company: Protein Crystallography Core Facility
      location: Carver College of Medicine, Unversity of Iowa, Iowa City, IA
      title: Protein Crystallography Core Staff
      started: 2011
      duration: (2011 - 2013)
      description: Contracted protein purification and characterization.  User training for protein expression, purification and crystallization.  Development of custom protocols for in-house robotic liquid handlers
  educationHistory:
    - education1:
      organization: Georgia Institute of Technology
      location: Atlanta, GA
      major: P,hD Bioinformatics (In progress))
      started: 2017
      duration: (2017 - Present)
      description: Studying the effects of human ancestry on disease burden in Colombia and South America.  Teaching and administrating classes in the Bioinformatics Master's program.  Development of bacterial typing schemes in collaboration with the Centers for Disease Control and Prevention
    - education2:
      organization: Georgia Institute of Technology
      location: Atlanta, GA
      major: Master of Science, Bioinformatics
      started: 2015
      duration: (2015 - 2016)
      description: Developed bacterial analysis pipelines and products.  https://vibriocholera.com
    - education3:
      organization: University of Iowa
      location: Iowa City, IA
      major: Bachelor of Science, Microbiology
      started: 2014
      duration: (2014 - 2015)
      description: Focusing on clinical microbiology and infectious disease
    - education4:
      organization: University of Iowa
      location: Iowa City, IA
      major: Bachelor of Science, Biology
      started: 2009
      duration: (2009 - 2013)
      description: Focusing on protein biochemistry
  languages:
    - language1:
      name: English
      proficiency: Native
    - language2:
      name: French
      proficiency: Limited
    - language3:
      name: Spanish
      proficiency: Limited
  programmingSkills:
    - skill1:
      name: Perl
      percentage: 100%
    - skill2:
      name: Bash / Linux
      percentage: 100%
    - skill3:
      name: Unix System Administration
      percentage: 80%
    - skill4:
      name: R
      percentage: 90%
    - skill5:
      name: Python
      percentage: 80%
