# Site settings
title: Aroon Chande's CV 
description: Aroon Chande's CV 
favicon: /assets/img/avatar.JPG
baseurl: https://www.aroonchan.de
url: https://www.aroonchan.de
rss_url: /pages/atom.xml
google_analytics: UA-45174995-10

# Build settings
markdown: kramdown

exclude: [vendor]

# Author settings
author:
  name: Aroon Chande
  title: Bioinformatics Scientist
  address: Atlanta, Georgia
  email: mail@aroonchande.com
  link: https://aroonchande.com
  github: ar0ch
  # linkedin: ddbullfrog
  # twitter: ddbullfrog
  gavatar: /assets/img/avatar.JPG
  # stackoverflow:
#  stackoverflow: 4582127
  workHistory:
    - work1:
      company: Applied Bioinformatics Laboratory
      location: 2 Ravinia Dr. Suite 1200, Atlanta GA 30346
      title: Bioinformatics Scientist
      started: 2016
      duration: (2016 - Present)
      description: 
    - work2:
  educationHistory:
    - education1:
      company: Georgia Institute of Technology
      location: Atlanta, GA
      title: PhD Student (Bioinformatics)
      started: 2017
      duration: (2017 - Present)
      description: 
    - education2:
      company: Georgia Institute of Technology
      location: Atlanta, GA
      title: Master of Science, Bioinformatics
      started: 2015
      duration: (2015 - 2016)
      description: 
    - education3:
      company: University of Iowa
      location: Iowa City, IA
      title: Bachellor of Science, Microbiology
      started: 2014
      duration: (2014 - 2015)
      description:
    - education3:
      company: University of Iowa
      location: Iowa City, IA
      title: Bachellor of Science, Biology
      started: 2009
      duration: (2009 - 2013)
      description: 
  languages:
    - language1:
      name: English
      proficiency: Native
    - language2:
      name: French
      proficiency: Limited
    - language3:
      name: Spanish
      proficiency: Limited
  programmingSkills:
    - skill1:
      name: Perl
      percentage: 100%
    - skill2:
      name: Bash / Linux
      percentage: 100%
    - skill3:
      name: Unix System Administration
      percentage: 80%
    - skill4:
      name: R
      percentage: 90%
    - skill5:
      name: Python
      percentage: 80%
